import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

final GetIt sl = GetIt.instance;

// For this blueprint we are using manual setup since code generation
// requires running build_runner, but we mark it for completeness.

@InjectableInit(
  initializerName: 'init', 
  preferRelativeImports: true, 
  asExtension: true,
)
Future<void> configureDependencies() async {
  // In a real project, this would call sl.init() generated by injectable.
  // We will manually register dependencies as needed for the blueprint.
}
